// Automatically Generated by Next.js
/// <reference types="next" />
/// <reference types="next/types/global" />

// Configure Styled Components CSS prop with TypeScript
import * as types from "styled-components/cssprop";

// Configure Styled Components to reference our theme schema.
import "styled-components";
import { Theme } from "./styles/themes/types";

declare module "styled-components" {
  export interface DefaultTheme extends Theme {}
}
